-- KPITB Data Analytics LMS Questions Database Seed File
-- Exactly 20 premium questions per week for Weeks 1 to 14 (Total 280 MCQs)
-- Evaluated from Easy to Hard

TRUNCATE TABLE public.questions CASCADE;

INSERT INTO public.questions (week_number, question_text, option_a, option_b, option_c, option_d, correct, marks, sort_order)
VALUES
  (1, 'Which type of analytics answers ''What happened?''', 'Predictive', 'Descriptive', 'Prescriptive', 'Diagnostic', 'B', 2, 1),
  (1, 'Which type of analytics answers ''Why did it happen?''', 'Descriptive', 'Predictive', 'Prescriptive', 'Diagnostic', 'D', 2, 2),
  (1, 'A business report showing the total revenue of the last quarter is an example of:', 'Diagnostic analytics', 'Descriptive analytics', 'Predictive analytics', 'Prescriptive analytics', 'B', 2, 3),
  (1, 'Which role is primarily responsible for cleaning data and creating dashboards?', 'Data Analyst', 'Data Engineer', 'Machine Learning Engineer', 'DevOps Engineer', 'A', 2, 4),
  (1, 'What is the primary goal of data analytics in a business context?', 'To write complex code', 'To store as much data as possible', 'To make data-driven decisions', 'To replace human employees', 'C', 2, 5),
  (1, 'A hospital uses historical patient data to predict readmission rates next month. This is:', 'Descriptive', 'Diagnostic', 'Predictive', 'Prescriptive', 'C', 2, 6),
  (1, 'A GPS navigation app recommending a faster route dynamically in real-time is an example of:', 'Descriptive', 'Diagnostic', 'Predictive', 'Prescriptive', 'D', 2, 7),
  (1, 'Customer feedback categorized as ''Good'', ''Average'', or ''Bad'' represents which type of data scale?', 'Nominal', 'Ordinal', 'Interval', 'Ratio', 'B', 2, 8),
  (1, 'A user''s gender (e.g., Male, Female, Other) represents which scale of measurement?', 'Nominal', 'Ordinal', 'Interval', 'Ratio', 'A', 2, 9),
  (1, 'Which of the following is a quantitative discrete variable?', 'The weight of a package', 'The temperature of a room', 'The number of active users in an app', 'The monthly revenue in USD', 'C', 2, 10),
  (1, 'Which scale of measurement contains an absolute, non-arbitrary zero point?', 'Nominal', 'Ordinal', 'Interval', 'Ratio', 'D', 2, 11),
  (1, 'What is a major limitation of descriptive analytics?', 'It requires machine learning models', 'It only looks at past data and cannot explain why something happened', 'It is too expensive to run', 'It cannot be visualized', 'B', 2, 12),
  (1, 'A company analyzes server log patterns to find why their app crashed yesterday. This is:', 'Descriptive analytics', 'Diagnostic analytics', 'Predictive analytics', 'Prescriptive analytics', 'B', 2, 13),
  (1, 'An indicator that helps forecast future trends or events is called a:', 'Lagging indicator', 'Leading indicator', 'Coincident indicator', 'Vanity metric', 'B', 2, 14),
  (1, 'Total gross sales at the end of a fiscal year is an example of a:', 'Leading indicator', 'Lagging indicator', 'Predictive indicator', 'Actionable indicator', 'B', 2, 15),
  (1, 'In the NOIR scale, which scale represents temperature in Fahrenheit (where 0 degrees does not mean ''no temperature'')?', 'Nominal', 'Ordinal', 'Interval', 'Ratio', 'C', 2, 16),
  (1, 'What is the primary difference between a metric and a KPI?', 'KPIs are always financial; metrics are not', 'A KPI is a metric that is directly tied to a key strategic business objective', 'Metrics are calculated automatically; KPIs must be manual', 'Metrics look at the past; KPIs look at the future', 'B', 2, 17),
  (1, 'Which of the following is considered a ''vanity metric'' in mobile app analytics?', 'Daily Active Users (DAU)', 'Customer Acquisition Cost (CAC)', 'Total number of app downloads', 'Monthly Churn Rate', 'C', 2, 18),
  (1, 'Why does prescriptive analytics have the highest complexity and business value?', 'It uses simple spreadsheet formulas', 'It requires clean databases', 'It determines optimal courses of action and automates decision-making recommendations', 'It is only used by executives', 'C', 2, 19),
  (1, 'An analyst discovers that their sales prediction model is consistently overestimating revenue by 10% due to historical patterns. This is known as:', 'Selection bias', 'Sampling error', 'Model bias', 'Data latency', 'C', 2, 20),
  (2, 'What is the first step in the data lifecycle?', 'Cleaning', 'Exploration', 'Collection', 'Visualization', 'C', 2, 1),
  (2, 'In which phase of the data lifecycle do you remove duplicate rows and fix formatting errors?', 'Collection', 'Cleaning', 'Analysis', 'Decision', 'B', 2, 2),
  (2, 'Which data lifecycle stage involves creating charts and dashboards?', 'Cleaning', 'Visualization', 'Storage', 'Collection', 'B', 2, 3),
  (2, 'What does the ''S'' in the SMART KPI framework stand for?', 'Simple', 'Standard', 'Specific', 'Structured', 'C', 2, 4),
  (2, 'What does the ''M'' in the SMART KPI framework stand for?', 'Manageable', 'Measurable', 'Monetized', 'Minimal', 'B', 2, 5),
  (2, 'An analyst is scrape-collecting public job listings from a website. This is an example of:', 'Primary data collection', 'Secondary data collection', 'Data transformation', 'Data governance', 'B', 2, 6),
  (2, 'Which of the following describes a ''Data Lake''?', 'A structured relational database system', 'A storage repository that holds raw, unstructured data in its native format', 'A cleaned, aggregate database optimized for business analysts', 'A cloud server for hosting web apps', 'B', 2, 7),
  (2, 'What is the purpose of exploratory data analysis (EDA)?', 'To build final production machine learning models', 'To summarize data main characteristics and spot anomalies before modeling', 'To publish public research documents', 'To secure cloud storage permissions', 'B', 2, 8),
  (2, 'If a business goal is ''Increase customer satisfaction by Q4'', which metric is the most relevant KPI?', 'Net Promoter Score (NPS)', 'Cost Per Click (CPC)', 'Total Website Visits', 'Employee Turnover Rate', 'A', 2, 9),
  (2, 'Which phase of the data lifecycle takes up the largest percentage of an analyst''s time?', 'Visualization', 'Data Collection', 'Data Cleaning and Preparation', 'Reporting', 'C', 2, 10),
  (2, 'A KPI is ''Time-bound'' when it:', 'Has no deadline', 'Must be measured in real-time', 'Is tied to a specific target timeframe (e.g. within 6 months)', 'Is calculated hourly', 'C', 2, 11),
  (2, 'Which of the following is a leading indicator for a sales pipeline?', 'Quarterly revenue closed', 'Number of outbound sales calls made', 'Customer retention rate', 'Profit margin per client', 'B', 2, 12),
  (2, 'Why is data profiling important during the initial collection phase?', 'To format Excel cells', 'To understand data quality, structure, and check for anomalies', 'To automatically correct typos', 'To build predictive models', 'B', 2, 13),
  (2, 'A dashboard is updated once every 24 hours. This data latency is considered:', 'Real-time', 'Near real-time', 'Batch/Daily', 'Streaming', 'C', 2, 14),
  (2, 'Which type of database schema is typically optimized for analytical queries (OLAP)?', 'Normalized transactional schema', 'Star schema with dimension and fact tables', 'Unstructured document schema', 'Key-value schema', 'B', 2, 15),
  (2, 'What is the primary difference between a Data Warehouse and a Data Lake?', 'Data lakes are only on-premise; warehouses are cloud-only', 'Warehouses store highly structured data ready for analysis; lakes store raw unstructured data', 'Warehouses are cheaper than lakes', 'Data lakes do not support SQL', 'B', 2, 16),
  (2, 'If a company has a KPI that is ''Relevant'' but NOT ''Measurable'', what is the result?', 'The KPI is perfect for C-Suite reporting', 'It is impossible to track progress objectively since there is no numeric metric', 'The KPI cannot have a time boundary', 'It becomes a leading indicator', 'B', 2, 17),
  (2, 'A web analyst tracks user visits via browser cookies. Which ethical concern is most prominent here?', 'Data accuracy', 'User privacy and consent', 'Data storage costs', 'Algorithm bias', 'B', 2, 18),
  (2, 'An analyst deletes rows containing missing data without evaluating the pattern of missingness. This risks:', 'Decreasing storage costs', 'Introducing selection bias and distorting analysis results', 'Optimizing query speed', 'Automatically correcting outliers', 'B', 2, 19),
  (2, 'Which metadata category describes the structure of data (e.g., table schemas, indexes, data types)?', 'Descriptive metadata', 'Administrative metadata', 'Structural metadata', 'Statistical metadata', 'C', 2, 20),
  (3, 'Which of the following represents the basic equation for Net Profit?', 'Revenue – Taxes', 'Revenue – Cost of Goods Sold (COGS)', 'Revenue – Total Expenses', 'Gross Profit + COGS', 'C', 2, 1),
  (3, 'What does COGS stand for in business analytics?', 'Cost of Gross Sales', 'Cost of Goods Sold', 'Company Operating General Spend', 'Calculated Operations Gross Sum', 'B', 2, 2),
  (3, 'What is the formula for Gross Profit?', 'Revenue – COGS', 'Revenue – Operating Expenses', 'Net Profit + Taxes', 'EBITDA – Interest', 'A', 2, 3),
  (3, 'Which metric calculates the total money earned from sales before any deductions?', 'Net profit', 'EBITDA', 'Gross revenue', 'Operating income', 'C', 2, 4),
  (3, 'What does ROI stand for?', 'Return on Investment', 'Rate of Interest', 'Revenue on Input', 'Retained Operating Income', 'A', 2, 5),
  (3, 'If a company spends PKR 500,000 on marketing and acquires 250 new customers, what is the Customer Acquisition Cost (CAC)?', 'PKR 1,000', 'PKR 2,000', 'PKR 2,500', 'PKR 5,000', 'B', 2, 6),
  (3, 'Customer Lifetime Value (LTV) represents:', 'The total revenue a customer generates in their first purchase', 'The net profit attributed to the entire future relationship with a customer', 'The marketing cost to retain a customer for one year', 'The time a customer spends on the website', 'B', 2, 7),
  (3, 'A healthy LTV:CAC ratio for a growing SaaS business is typically considered to be:', '1:1', '1:3', '3:1 or higher', '10:1 or lower', 'C', 2, 8),
  (3, 'What does EBITDA measure?', 'A company''s net income after tax', 'A company''s operating performance before non-operating decisions and accounting bookkeeping', 'The total valuation of a company on the stock market', 'The rate of customer churn', 'B', 2, 9),
  (3, 'Which cost remains constant regardless of the volume of goods produced?', 'Variable Cost', 'Direct Cost', 'Fixed Cost', 'Marginal Cost', 'C', 2, 10),
  (3, 'If a product costs PKR 400 to make (COGS) and is sold for PKR 1,000, what is the Gross Profit Margin?', '40%', '60%', '150%', '250%', 'B', 2, 11),
  (3, 'What is the break-even point in business operations?', 'When revenue exceeds expenses by 50%', 'When total revenue equals total costs (zero profit/loss)', 'When a company goes public', 'When Customer Acquisition Cost reaches zero', 'B', 2, 12),
  (3, 'A company has PKR 1,000,000 in revenue and PKR 150,000 in net profit. What is the Net Profit Margin?', '15%', '85%', '115%', '6.6%', 'A', 2, 13),
  (3, 'Which of the following is a variable cost in manufacturing?', 'Factory rent', 'Raw materials used in production', 'Executive salaries', 'Property insurance', 'B', 2, 14),
  (3, 'What is the main purpose of the Income Statement?', 'To show a company''s assets and liabilities at a specific point in time', 'To show revenue, expenses, and profit over a period of time', 'To track cash flows entering and leaving the bank', 'To list the equity of all shareholders', 'B', 2, 15),
  (3, 'What is the difference between the Income Statement and the Cash Flow Statement?', 'The Income statement tracks actual cash; Cash Flow tracks accounting accruals', 'The Income statement uses accrual accounting (earned revenue); Cash Flow tracks actual cash movements', 'They are identical documents with different names', 'Only public corporations prepare a Cash Flow Statement', 'B', 2, 16),
  (3, 'An analyst calculates that a SaaS company''s Monthly Recurring Revenue (MRR) Churn is 5%. What does this mean?', 'The company is losing 5% of its total customers every month', 'The company is losing 5% of its recurring revenue from existing customers every month', 'Marketing costs increased by 5%', 'Sales revenue grew by 5% compared to last month', 'B', 2, 17),
  (3, 'If an investment of PKR 2,000,000 generates PKR 2,600,000 in total return, what is the ROI?', '30%', '130%', '23%', '60%', 'A', 2, 18),
  (3, 'Which of the following represents working capital?', 'Current Assets + Current Liabilities', 'Current Assets – Current Liabilities', 'Total Assets – Total Liabilities', 'Fixed Assets – Long-term Debt', 'B', 2, 19),
  (3, 'What does the payback period measure in unit economics?', 'The time it takes for a customer to complete a checkout process', 'The time required to recover the Customer Acquisition Cost (CAC) from the gross margin of a customer', 'The duration of an interest-free loan', 'The lifespan of a customer contract', 'B', 2, 20),
  (4, 'In marketing analytics, what does CTR stand for?', 'Cost To Retain', 'Click-Through Rate', 'Customer Target Reach', 'Conversion Time Ratio', 'B', 2, 1),
  (4, 'Which stage of the marketing funnel represents a customer actually buying a product?', 'Awareness', 'Consideration', 'Conversion', 'Retention', 'C', 2, 2),
  (4, 'What does CRM stand for?', 'Customer Relationship Management', 'Customer Retention Metric', 'Calculated Risk Management', 'Company Resource Mapping', 'A', 2, 3),
  (4, 'In HR analytics, what is ''Employee Turnover Rate''?', 'The rate at which employees are promoted', 'The percentage of employees leaving the company over a period', 'The average hours employees work per week', 'The rate of hiring new interns', 'B', 2, 4),
  (4, 'Which metric tracks the percentage of website visitors who complete a desired action?', 'Conversion Rate', 'Bounce Rate', 'Exit Rate', 'Click Rate', 'A', 2, 5),
  (4, 'A marketing campaign gets 100 clicks from 5,000 impressions. What is the Click-Through Rate (CTR)?', '1%', '2%', '5%', '10%', 'B', 2, 6),
  (4, 'If an ad campaign costs PKR 100,000 and generates PKR 500,000 in revenue, what is the Return on Ad Spend (ROAS)?', '2x', '5x', '10x', '0.2x', 'B', 2, 7),
  (4, 'What does NPS stand for in customer experience metrics?', 'Net Profit Share', 'Net Promoter Score', 'New Product Sales', 'National Productivity Standard', 'B', 2, 8),
  (4, 'An NPS score is calculated by subtracting the percentage of Detractors from the percentage of:', 'Passives', 'Promoters', 'Buyers', 'Subscribers', 'B', 2, 9),
  (4, 'In operations analytics, the time elapsed between order placement and delivery is called:', 'Cycle Time', 'Lead Time', 'Throughput', 'Idle Time', 'B', 2, 10),
  (4, 'Which lean waste is represented by storing excess materials or finished products?', 'Overprocessing', 'Defects', 'Inventory', 'Motion', 'C', 2, 11),
  (4, 'A company hires 50 employees. During the year, 10 employees resign. What is the annual turnover rate?', '10%', '20%', '50%', '5%', 'B', 2, 12),
  (4, 'In the Lean manufacturing framework, what does the acronym ''TIMWOOD'' represent?', 'A project management scheduling system', 'The 7 classic wastes (Transportation, Inventory, Motion, Waiting, Overproduction, Overprocessing, Defects)', 'A statistical quality control method', 'A technique for database indexing', 'B', 2, 13),
  (4, 'What is the primary focus of ''Throughput'' analysis in operations?', 'The amount of data stored in servers', 'The rate at which a system produces its output products over time', 'The marketing costs per unit sold', 'The retention rate of factory workers', 'B', 2, 14),
  (4, 'Which metric calculates the total cost associated with hiring a new employee?', 'CAC', 'Cost Per Hire (CPH)', 'LTV', 'Salary Cap', 'B', 2, 15),
  (4, 'What does an RFM analysis stand for in customer segmentation?', 'Recency, Frequency, Monetary Value', 'Reach, Frequency, Marketing Margin', 'Revenue, Forecast, Margin', 'Retention, Feedback, Mediation', 'A', 2, 16),
  (4, 'In marketing attribution, which model gives 100% of the conversion credit to the very first ad touchpoint?', 'Last-Interaction Model', 'First-Interaction Model', 'Linear Model', 'Time-Decay Model', 'B', 2, 17),
  (4, 'What is the difference between Lead Time and Cycle Time in Kanban/Operations?', 'Lead Time starts when work begins; Cycle Time starts when customer requests it', 'Lead Time starts when customer requests it; Cycle Time starts when active work begins on it', 'They are identical measures of time', 'Cycle Time is always longer than Lead Time', 'B', 2, 18),
  (4, 'How is Net Promoter Score (NPS) categorized based on user ratings (0 to 10 scale)?', '0-4 Detractors, 5-8 Passives, 9-10 Promoters', '0-6 Detractors, 7-8 Passives, 9-10 Promoters', '0-5 Detractors, 6-7 Passives, 8-10 Promoters', '0-7 Detractors, 8-9 Passives, 10 Promoters', 'B', 2, 19),
  (4, 'In HR analytics, what is the ''Revenue per FTE'' metric used for?', 'To calculate individual payroll taxes', 'To evaluate workforce productivity by dividing total company revenue by full-time equivalent employees', 'To measure customer satisfaction', 'To track onboarding costs', 'B', 2, 20),
  (5, 'Which measure of central tendency represents the mathematical average?', 'Median', 'Mode', 'Mean', 'Range', 'C', 2, 1),
  (5, 'Which measure of central tendency represents the exact middle value in a sorted dataset?', 'Mean', 'Median', 'Mode', 'Variance', 'B', 2, 2),
  (5, 'What is the mode in a dataset?', 'The difference between the max and min values', 'The value that appears most frequently', 'The middle value when sorted', 'The square root of variance', 'B', 2, 3),
  (5, 'Which statistic is calculated by subtracting the minimum value from the maximum value?', 'Interquartile Range (IQR)', 'Standard Deviation', 'Range', 'Variance', 'C', 2, 4),
  (5, 'The square root of variance is equal to:', 'Range', 'Mean Absolute Deviation', 'Standard Deviation', 'Quartile Deviation', 'C', 2, 5),
  (5, 'In a dataset with extreme outliers, which measure of center is the most robust and least affected?', 'Mean', 'Median', 'Mode', 'Range', 'B', 2, 6),
  (5, 'If a dataset has a mean of 120 and a median of 80, the distribution is most likely:', 'Symmetrical', 'Left-skewed (negative)', 'Right-skewed (positive)', 'Normal', 'C', 2, 7),
  (5, 'How do you calculate the Interquartile Range (IQR)?', 'Max – Min', 'Q3 – Q1', 'Q2 – Q1', 'Mean – Median', 'B', 2, 8),
  (5, 'According to the IQR outlier detection rule, a value is an outlier if it is less than Q1 by more than:', '1.0 × IQR', '1.5 × IQR', '2.0 × IQR', '3.0 × IQR', 'B', 2, 9),
  (5, 'In a perfectly symmetrical normal distribution:', 'Mean > Median > Mode', 'Mean < Median < Mode', 'Mean = Median = Mode', 'Mean and Median are equal, but Mode is different', 'C', 2, 10),
  (5, 'Which standard deviation value represents the highest dispersion/spread in a dataset?', 'SD = 0', 'SD = 1.5', 'SD = 10', 'SD = 250', 'D', 2, 11),
  (5, 'A box plot visually displays which of the following summaries?', 'The 5-number summary (Min, Q1, Median, Q3, Max)', 'The mean and standard deviation', 'The probability density function', 'The regression trendline', 'A', 2, 12),
  (5, 'What is the empirical rule percentage of data falling within 1 Standard Deviation in a normal distribution?', '50%', '68%', '95%', '99.7%', 'B', 2, 13),
  (5, 'What is the empirical rule percentage of data falling within 2 Standard Deviations in a normal distribution?', '68%', '75%', '95%', '99.7%', 'C', 2, 14),
  (5, 'If standard deviation is 5, what is the variance?', '2.23', '10', '25', '50', 'C', 2, 15),
  (5, 'What does a Kurtosis value greater than 3 indicate about a distribution?', 'It is flatter than a normal distribution', 'It has heavier tails and a higher peak (leptokurtic) compared to a normal distribution', 'It is heavily skewed to the left', 'It is a uniform distribution', 'B', 2, 16),
  (5, 'Why is variance expressed in squared units of the original variable?', 'Because standard deviation is too small', 'Due to squaring the differences from the mean to prevent positive and negative differences canceling each other out', 'To make it easier to graph', 'It is only a historical convention with no mathematical purpose', 'B', 2, 17),
  (5, 'A dataset has Q1 = 30 and Q3 = 70. Which of the following values is flagged as an outlier?', '0', '45', '100', '135', 'D', 2, 18),
  (5, 'What is the coefficient of variation (CV) used for?', 'To measure absolute skewness', 'To compare the relative variability of datasets with different units or means (SD divided by Mean)', 'To calculate the regression slope', 'To determine the median of non-numeric data', 'B', 2, 19),
  (5, 'A distribution has a long tail pointing towards smaller/negative values. This is:', 'Right-skewed', 'Left-skewed', 'Platykurtic', 'Symmetric', 'B', 2, 20),
  (6, 'Which hypothesis represents the statement of ''no effect'' or ''no difference''?', 'Alternative Hypothesis (H1)', 'Null Hypothesis (H0)', 'Research Hypothesis', 'Unilateral Hypothesis', 'B', 2, 1),
  (6, 'What is the probability of an event that is absolutely certain to happen?', '0.0', '0.5', '1.0', '100.0', 'C', 2, 2),
  (6, 'In hypothesis testing, what alpha (α) value is most commonly used as the threshold for significance?', '0.01', '0.05', '0.10', '0.50', 'B', 2, 3),
  (6, 'What happens to the null hypothesis if your p-value is less than alpha (α)?', 'Fail to reject H0', 'Reject H0', 'Accept H0 as absolute truth', 'Modify the hypothesis', 'B', 2, 4),
  (6, 'A standard Z-score measures how many standard deviations a data point is from the:', 'Variance', 'Median', 'Mean', 'Range', 'C', 2, 5),
  (6, 'Rejecting a true null hypothesis is known as a:', 'Type I Error', 'Type II Error', 'Standard Error', 'Sampling Bias', 'A', 2, 6),
  (6, 'Failing to reject a false null hypothesis is known as a:', 'Type I Error', 'Type II Error', 'Standard Error', 'Confidence Error', 'B', 2, 7),
  (6, 'If you test a drug and find p-value = 0.02, using α = 0.05, what is your conclusion?', 'The drug has no effect (Accept H0)', 'The drug has a statistically significant effect (Reject H0)', 'The study is invalid', 'Run the test again with a different mean', 'B', 2, 8),
  (6, 'A Pearson correlation coefficient (r) of –0.85 indicates a:', 'Strong positive relationship', 'Weak negative relationship', 'Strong negative relationship', 'No relationship', 'C', 2, 9),
  (6, 'Which probability distribution describes the number of successes in a fixed number of independent trials?', 'Normal Distribution', 'Poisson Distribution', 'Binomial Distribution', 'Exponential Distribution', 'C', 2, 10),
  (6, 'Which distribution is best used to model the number of customer arrivals in a store per hour?', 'Binomial', 'Poisson', 'Uniform', 'Normal', 'B', 2, 11),
  (6, 'What does the Central Limit Theorem (CLT) state about the sampling distribution of the mean?', 'It will be skewed if the population is skewed', 'It approaches a normal distribution as sample size gets large, regardless of the population distribution', 'The variance increases with sample size', 'It is identical to the population distribution', 'B', 2, 12),
  (6, 'Which test is most appropriate to compare the means of exactly two independent groups?', 'Chi-Square Test', 'One-Way ANOVA', 'Independent Samples t-test', 'Pearson Correlation', 'C', 2, 13),
  (6, 'Which test compares the means of three or more independent groups?', 't-test', 'ANOVA', 'Chi-Square Test of Independence', 'Linear Regression', 'B', 2, 14),
  (6, 'A data quality dimension that measures if all required values are present in a table is:', 'Accuracy', 'Consistency', 'Completeness', 'Uniqueness', 'C', 2, 15),
  (6, 'If you increase the significance level (alpha) from 0.01 to 0.05, what happens to the error probabilities?', 'Type I error decreases, Type II increases', 'Type I error increases, Type II decreases', 'Both errors decrease', 'Both errors increase', 'B', 2, 16),
  (6, 'What is statistical power?', 'The probability of committing a Type I Error', 'The probability of correctly rejecting a false null hypothesis (1 – Beta)', 'The size of the population sample', 'The calculation speed of the database', 'B', 2, 17),
  (6, 'When is a Chi-Square Test of Independence used?', 'To compare the means of two numeric variables', 'To determine if there is a significant relationship between two categorical variables', 'To model a trend over time', 'To identify numeric outliers', 'B', 2, 18),
  (6, 'What is the difference between correlation and causation?', 'Correlation implies causation in large datasets', 'Correlation measures linear association; causation means one variable directly changes the other', 'Causation is easier to prove than correlation', 'They are mathematically identical', 'B', 2, 19),
  (6, 'An analyst discovers data has missing values that depend on other observed variables. This missingness is:', 'Missing Completely at Random (MCAR)', 'Missing at Random (MAR)', 'Missing Not at Random (MNAR)', 'Complete missingness', 'B', 2, 20),
  (7, 'Which Excel formula is used to look up values in the first column of a range and return a value in the same row?', 'HLOOKUP', 'VLOOKUP', 'INDEX', 'MATCH', 'B', 2, 1),
  (7, 'Which character must every Excel formula begin with?', '+', '=', '@', '#', 'B', 2, 2),
  (7, 'Which formula adds values in a range that meet a specific single condition?', 'SUM', 'SUMIF', 'SUMIFS', 'COUNTIF', 'B', 2, 3),
  (7, 'Which formula counts the number of cells in a range that contain numbers?', 'COUNTA', 'COUNTIF', 'COUNT', 'COUNTBLANK', 'C', 2, 4),
  (7, 'How do you lock a cell reference (make it absolute) in an Excel formula?', 'Add # before letters', 'Surround with quotes', 'Add $ before column and row references', 'Press Ctrl+L', 'C', 2, 5),
  (7, '=VLOOKUP(A2, D:F, 3, FALSE) searches for the value in A2 in which column?', 'Column D', 'Column E', 'Column F', 'Column A', 'A', 2, 6),
  (7, 'Why is XLOOKUP preferred over VLOOKUP in modern Excel?', 'It is slower but more accurate', 'It can search to the left, defaults to exact match, and doesn''t require column index numbers', 'It only works with numbers', 'It automatically creates charts', 'B', 2, 7),
  (7, 'What does the MATCH function return in Excel?', 'The actual value of the cell found', 'The relative position (row/column index) of the item in a range', 'A boolean TRUE/FALSE', 'An error if duplicates exist', 'B', 2, 8),
  (7, 'Which function returns a value you specify if a formula evaluates to an error?', 'IF', 'AND', 'IFERROR', 'ERROR.TYPE', 'C', 2, 9),
  (7, 'What is the output of =IF(10 > 5, ''Yes'', ''No'')?', 'Yes', 'No', 'True', 'Error', 'A', 2, 10),
  (7, 'To sum sales where Region is ''West'' AND Product is ''Widget'', which formula must you use?', 'SUMIF', 'SUMIFS', 'SUM+IF', 'DSUM', 'B', 2, 11),
  (7, 'Which function joins multiple text strings into one and allows specifying a delimiter (e.g., a comma)?', 'CONCAT', 'TEXTJOIN', 'MERGE', 'JOIN', 'B', 2, 12),
  (7, 'What does a relative reference like A1 do when you copy a formula down one row?', 'It stays A1', 'It changes to B1', 'It changes to A2', 'It returns an error', 'C', 2, 13),
  (7, 'Which function extracts a specific number of characters from the middle of a text string?', 'LEFT', 'RIGHT', 'MID', 'FIND', 'C', 2, 14),
  (7, 'How does INDEX/MATCH work together to replace VLOOKUP?', 'INDEX finds the row position, MATCH returns the value', 'MATCH finds the relative position, INDEX returns the value from that position', 'They concatenate the text fields', 'They run a SQL query', 'B', 2, 15),
  (7, 'What does the error #N/A mean in a lookup formula?', 'The formula name is misspelled', 'A value is not available to the formula (lookup value not found)', 'Division by zero', 'The column reference is invalid', 'B', 2, 16),
  (7, 'What does =COUNTA(A1:A10) do?', 'Counts only numeric cells in the range', 'Counts all non-empty cells in the range (text, numbers, errors)', 'Counts only blank cells', 'Sums the values in the range', 'B', 2, 17),
  (7, 'What is the result of copying =$C1 down two rows and right one column?', '=$C2', '=$D3', '=$C3', '=$D1', 'C', 2, 18),
  (7, 'Which Excel feature allows you to automatically color cells based on their numeric values?', 'Conditional Formatting', 'Data Validation', 'Pivot Tables', 'Format Painter', 'A', 2, 19),
  (7, 'What is the result of the array formula =SUM((A1:A10>5)*(B1:B10))?', 'Sums B1:B10 only if the corresponding cell in A1:A10 is greater than 5', 'Multiplies all values in A and B', 'Returns an error unless you press Enter', 'Counts cells greater than 5', 'A', 2, 20),
  (8, 'What does ETL stand for in data engineering?', 'Extract, Transfer, Load', 'Extract, Transform, Load', 'Evaluate, Test, Launch', 'Exchange, Translate, Link', 'B', 2, 1),
  (8, 'Which tool in Excel and Power BI is used to connect, clean, and transform data?', 'PivotChart', 'Power Query', 'Data Analysis Expressions (DAX)', 'Power View', 'B', 2, 2),
  (8, 'In Power Query, which operation joins two tables by matching rows based on key columns (like SQL JOIN)?', 'Append Queries', 'Merge Queries', 'Pivot Columns', 'Group By', 'B', 2, 3),
  (8, 'In Power Query, which operation stacks rows of one table on top of another (like SQL UNION)?', 'Merge Queries', 'Append Queries', 'Unpivot Columns', 'Transpose', 'B', 2, 4),
  (8, 'Which transformation converts columns into row-attribute pairs, turning wide data into tall data?', 'Pivot Column', 'Unpivot Columns', 'Group By', 'Transpose', 'B', 2, 5),
  (8, 'What is ''Query Folding'' in Power Query?', 'Compressing queries to save disk space', 'Pushing data transformations back to the source database to run as SQL for optimization', 'Deleting unused queries', 'Combining multiple steps into one', 'B', 2, 6),
  (8, 'Which formula language is used under the hood in Power Query?', 'SQL', 'M Formula Language', 'DAX', 'VBA', 'B', 2, 7),
  (8, 'If you want to replace null values in a column with 0, which Power Query feature is best?', 'Filter Rows', 'Replace Values', 'Split Column', 'Remove Duplicates', 'B', 2, 8),
  (8, 'A column contains ''Firstname Lastname'' in one cell. Which feature splits this into two columns?', 'Merge Columns', 'Split Column by Delimiter', 'Unpivot', 'Group By', 'B', 2, 9),
  (8, 'What does the ''Column Quality'' profiling tool show in Power Query?', 'Average and median values', 'Percentage of Valid, Error, and Empty cells in each column', 'Total bytes used by the column', 'The index status of the column', 'B', 2, 10),
  (8, 'To clean leading and trailing whitespace from text fields, which command should you use?', 'Clean', 'Trim', 'Lowercase', 'Replace', 'B', 2, 11),
  (8, 'What is a major advantage of using Power Query over manual cleaning in Excel?', 'It runs faster formulas', 'It records cleaning steps as a reusable recipe that can be refreshed automatically', 'It has more colors', 'It doesn''t require saving files', 'B', 2, 12),
  (8, 'Which data type icon represents a Date/Time in Power Query?', '123', 'ABC', 'Calendar/Clock icon', 'TRUE/FALSE', 'C', 2, 13),
  (8, 'What happens to the source data file when you clean it in Power Query?', 'The source file is modified and overwritten', 'The source data remains untouched; Power Query only reads and transforms a copy', 'The source file is deleted', 'The source data is locked for other users', 'B', 2, 14),
  (8, 'Which operation aggregates multiple rows based on category columns in Power Query?', 'Group By', 'Merge', 'Pivot', 'Unpivot', 'A', 2, 15),
  (8, 'What is the difference between Merge Queries and Append Queries?', 'Merge adds columns; Append adds rows', 'Merge adds rows; Append adds columns', 'Merge is for Excel; Append is for SQL', 'They are identical operations', 'A', 2, 16),
  (8, 'When data is loaded into Power BI''s memory from Power Query, which storage mode is active by default?', 'DirectQuery', 'Import Mode', 'Dual Mode', 'Live Connection', 'B', 2, 17),
  (8, 'Why might a step in Power Query block Query Folding?', 'Using simple filters', 'Renaming columns', 'Using complex operations or custom functions that the source database cannot execute in SQL', 'Removing duplicate rows', 'C', 2, 18),
  (8, 'An analyst wants to add a column that calculates tax based on multiple conditional tiers. Which tool is best?', 'Custom Column using M', 'Conditional Column interface', 'Index Column', 'Format Column', 'B', 2, 19),
  (8, 'If Column Profile shows ''Distinct = 100, Unique = 100'' for 100 rows, this column is suitable as a:', 'Fact metric', 'Primary Key', 'Foreign Key', 'Aggregate Group', 'B', 2, 20),
  (9, 'Which SQL keyword is used to retrieve data from a database?', 'GET', 'SELECT', 'EXTRACT', 'OPEN', 'B', 2, 1),
  (9, 'Which clause is used to filter records based on a condition?', 'GROUP BY', 'WHERE', 'ORDER BY', 'HAVING', 'B', 2, 2),
  (9, 'Which clause sorts the result set in ascending or descending order?', 'SORT BY', 'ORDER BY', 'GROUP BY', 'ARRANGE', 'B', 2, 3),
  (9, 'Which SQL JOIN returns only the rows that have matching values in both tables?', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL OUTER JOIN', 'C', 2, 4),
  (9, 'Which SQL function returns the total number of rows in a query?', 'SUM()', 'TOTAL()', 'COUNT()', 'ADD()', 'C', 2, 5),
  (9, 'What is the difference between WHERE and HAVING in SQL?', 'WHERE filters rows before aggregation; HAVING filters aggregated groups', 'WHERE filters groups; HAVING filters rows', 'They are identical and interchangeable', 'WHERE is only for SELECT; HAVING is only for UPDATE', 'A', 2, 6),
  (9, 'Which SQL JOIN returns all rows from the left table, and matching rows from the right table?', 'INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'CROSS JOIN', 'B', 2, 7),
  (9, 'What does SELECT COUNT(DISTINCT City) FROM Customers do?', 'Counts all rows in the table', 'Counts unique non-duplicate cities in the Customers table', 'Lists all unique cities', 'Returns an error', 'B', 2, 8),
  (9, 'Which operator is used to search for a specified pattern in a column (e.g. name starting with ''A'')?', 'IN', 'BETWEEN', 'LIKE', 'MATCH', 'C', 2, 9),
  (9, 'To get the highest salary from an Employees table, which function should you use?', 'HIGH()', 'MAX()', 'TOP()', 'SUM()', 'B', 2, 10),
  (9, 'What does the SQL statement SELECT * FROM Products WHERE Price BETWEEN 10 AND 50 do?', 'Selects products priced strictly at 10 or 50', 'Selects products priced from 10 to 50 inclusive', 'Selects products priced below 10 or above 50', 'Calculates average price', 'B', 2, 11),
  (9, 'Which SQL command deletes all data from a table without deleting the table structure itself?', 'DROP TABLE', 'DELETE TABLE', 'TRUNCATE TABLE', 'REMOVE TABLE', 'C', 2, 12),
  (9, 'What is a Foreign Key in a database schema?', 'A key used to encrypt table data', 'A column in one table that points to the Primary Key of another table to establish a link', 'A primary key from an external database', 'An unused index', 'B', 2, 13),
  (9, 'Which wildcard character in a SQL LIKE clause matches zero or more characters?', '?', '*', '%', '_', 'C', 2, 14),
  (9, 'What does the SQL command GROUP BY do?', 'Sorts the output rows', 'Combines rows with identical values in specified columns into summary rows', 'Filters null values', 'Creates database indexes', 'B', 2, 15),
  (9, 'What is the default sort order of the ORDER BY clause?', 'Ascending (ASC)', 'Descending (DESC)', 'Random', 'Index order', 'A', 2, 16),
  (9, 'Which function returns the first non-NULL value in a list of columns?', 'NVL()', 'ISNULL()', 'COALESCE()', 'NULLIF()', 'C', 2, 17),
  (9, 'A table has 10 rows. Table B has 5 rows. A CROSS JOIN between them yields how many rows?', '15', '50', '10', '5', 'B', 2, 18),
  (9, 'Why should you avoid using SELECT * in production analytics queries?', 'It is disabled in modern SQL databases', 'It increases network traffic, slows down query performance, and can break code if columns change', 'It returns duplicate rows', 'It requires admin permissions', 'B', 2, 19),
  (9, 'What is the SQL standard operator for ''Not Equal to''?', '!=', '<>', 'NOT', '~', 'B', 2, 20),
  (10, 'Which SQL keyword is used to define a Common Table Expression (CTE)?', 'DEFINE', 'WITH', 'AS', 'CREATE TEMP', 'B', 2, 1),
  (10, 'Window functions are defined by which SQL clause?', 'PARTITION BY', 'OVER', 'GROUP BY', 'WINDOW', 'B', 2, 2),
  (10, 'Which window function assigns a unique sequential integer to rows, starting at 1?', 'RANK()', 'DENSE_RANK()', 'ROW_NUMBER()', 'NTILE()', 'C', 2, 3),
  (10, 'Which SQL clause partitions rows into groups before applying a window function?', 'GROUP BY', 'PARTITION BY', 'DISTRIBUTE BY', 'ORDER BY', 'B', 2, 4),
  (10, 'What is a subquery?', 'A query that runs in the background', 'A query nested inside another query', 'A database index query', 'A query executed via API', 'B', 2, 5),
  (10, 'What is the difference between RANK() and DENSE_RANK() window functions?', 'RANK() skips numbers after ties; DENSE_RANK() does not skip', 'DENSE_RANK() skips numbers; RANK() does not', 'RANK() works only with partition; DENSE_RANK() does not', 'They are identical in all databases', 'A', 2, 6),
  (10, 'Which function accesses data from a previous row in the same result set without self-joining?', 'LEAD()', 'LAG()', 'FIRST_VALUE()', 'NTH_VALUE()', 'B', 2, 7),
  (10, 'Which function accesses data from a subsequent (following) row in the same result set?', 'LAG()', 'LEAD()', 'LAST_VALUE()', 'OFFSET()', 'B', 2, 8),
  (10, 'What does NTILE(4) do when applied to a result set of 100 rows?', 'Returns only the top 4 rows', 'Divides the rows into 4 equal groups (quartiles) numbered 1 to 4', 'Multiplies values by 4', 'Splits the table into 4 databases', 'B', 2, 9),
  (10, 'A CTE defined with WITH is available for how long?', 'Permanently in the database', 'Only for the duration of the single query execution it is attached to', 'Until the user logs out', 'For 24 hours', 'B', 2, 10),
  (10, 'Which of the following is a non-correlated subquery?', 'A subquery that references columns from the outer query', 'A subquery that can be executed independently of the outer query', 'A subquery that runs recursively', 'A subquery that returns multiple columns', 'B', 2, 11),
  (10, 'What is the database execution plan used for?', 'To write the SQL syntax for you', 'To show how the database engine intends to execute the query and locate bottlenecks', 'To back up tables automatically', 'To schedule database migrations', 'B', 2, 12),
  (10, 'Which index type physically reorders the data rows in a table based on the key?', 'Non-clustered Index', 'Clustered Index', 'Bitmap Index', 'Full-text Index', 'B', 2, 13),
  (10, 'How many clustered indexes can exist on a single SQL table?', 'One', 'Unlimited', 'Two', 'None', 'A', 2, 14),
  (10, 'What is the purpose of query optimization in database administration?', 'To decrease the number of SQL characters used', 'To reduce execution time, CPU usage, and memory consumption during queries', 'To format column headers beautifully', 'To encrypt database tables', 'B', 2, 15),
  (10, 'What is the difference between a Temp Table (#table) and a CTE?', 'Temp tables are stored physically in TempDB; CTEs are virtual query expressions', 'CTEs are stored in TempDB; Temp tables are memory-only', 'CTEs support indexing; Temp tables do not', 'They are identical in performance', 'A', 2, 16),
  (10, 'Which window function clause defines a sliding offset window of rows (e.g. rolling 3-day average)?', 'PARTITION BY', 'ROWS BETWEEN', 'ORDER BY', 'FILTER GROUP', 'B', 2, 17),
  (10, 'A correlated subquery is typically:', 'Slower because it executes once for every row processed by the outer query', 'Faster than a join', 'Executed once globally before the outer query runs', 'Used only for inserts', 'A', 2, 18),
  (10, 'What does the SQL command EXPLAIN do before a query?', 'Executes the query and times it', 'Returns a text description of the database query planner execution strategy', 'Automatically fixes syntax errors', 'Formats SQL code', 'B', 2, 19),
  (10, 'Which JOIN type should you use to locate orphaned rows in a table that have no matches in another table?', 'INNER JOIN', 'LEFT JOIN checking for NULLs in the right table', 'CROSS JOIN', 'NATURAL JOIN', 'B', 2, 20),
  (11, 'Which data structures are defined by key-value pairs in Python?', 'Lists', 'Tuples', 'Sets', 'Dictionaries', 'D', 2, 1),
  (11, 'In Python, which character is used to comment out code lines?', '//', '/*', '#', '--', 'C', 2, 2),
  (11, 'Which library is the industry standard for data manipulation and analysis in Python?', 'Matplotlib', 'Seaborn', 'Pandas', 'Scikit-learn', 'C', 2, 3),
  (11, 'What does df.head() do by default in Pandas?', 'Returns the last 5 rows of a DataFrame', 'Returns the first 5 rows of a DataFrame', 'Lists the column names', 'Plots a bar chart', 'B', 2, 4),
  (11, 'Which Pandas function is used to load a comma-separated values file into a DataFrame?', 'read_excel()', 'read_csv()', 'load_csv()', 'open_file()', 'B', 2, 5),
  (11, 'What is the difference between loc and iloc in Pandas?', 'loc is for index labels; iloc is for integer-based positions', 'iloc is for index labels; loc is for positions', 'loc only works with text; iloc only works with numbers', 'They are identical in all versions', 'A', 2, 6),
  (11, 'Which DataFrame attribute returns a tuple representing the number of rows and columns?', 'shape', 'size', 'ndim', 'columns', 'A', 2, 7),
  (11, 'Which DataFrame method provides summary statistics (mean, standard deviation, min, max) for numeric columns?', 'info()', 'describe()', 'values', 'head()', 'B', 2, 8),
  (11, 'To count the number of missing (NaN) values in each column of a DataFrame, which code should you run?', 'df.isnull()', 'df.isnull().sum()', 'df.describe()', 'df.count()', 'B', 2, 9),
  (11, 'To drop all rows from a DataFrame containing any missing values, you use:', 'df.dropna()', 'df.fillna()', 'df.drop_nulls()', 'df.clean()', 'A', 2, 10),
  (11, 'To filter a DataFrame ''df'' for rows where ''Salary'' is greater than 50000, you use:', 'df.filter(Salary > 50000)', 'df[df[''Salary''] > 50000]', 'df.where(''Salary > 50000'')', 'df.select(''Salary > 50000'')', 'B', 2, 11),
  (11, 'Which Pandas method replaces missing NaN values with a specific value (like 0)?', 'dropna()', 'fillna()', 'replace_null()', 'interpolate()', 'B', 2, 12),
  (11, 'In Pandas, how do you rename a column ''OldName'' to ''NewName'' in a DataFrame?', 'df.rename(columns={''OldName'': ''NewName''})', 'df.rename(''OldName'', ''NewName'')', 'df.columns[''OldName''] = ''NewName''', 'df.replace_header()', 'A', 2, 13),
  (11, 'Which Pandas method is used to sort a DataFrame by a specific column''s values?', 'sort()', 'sort_values()', 'order_by()', 'arrange()', 'B', 2, 14),
  (11, 'What is the primary difference between a Series and a DataFrame in Pandas?', 'A Series is 2D; a DataFrame is 1D', 'A Series is a 1D labeled array (single column); a DataFrame is a 2D labeled tabular structure (multiple columns)', 'Series only stores text; DataFrames store numbers', 'Series does not support indexes', 'B', 2, 15),
  (11, 'How does the ''inplace=True'' parameter affect Pandas DataFrame operations?', 'It speeds up calculations using GPU', 'It modifies the original DataFrame directly rather than returning a new copy', 'It outputs a log file', 'It locks the DataFrame from edits', 'B', 2, 16),
  (11, 'To apply a custom function to every value in a Pandas column, which method is best?', 'apply()', 'map()', 'aggregate()', 'transform()', 'A', 2, 17),
  (11, 'What does the code ''df.duplicated().sum()'' do?', 'Lists all duplicate rows', 'Returns the count of duplicate rows in the DataFrame', 'Removes duplicate rows', 'Filters duplicate rows out', 'B', 2, 18),
  (11, 'To merge two DataFrames on a key column, which Pandas function should you use?', 'pd.concat()', 'pd.merge()', 'pd.append()', 'pd.stack()', 'B', 2, 19),
  (11, 'What is a lambda function in Python?', 'A package used for mathematical calculations', 'An anonymous, inline, one-line function defined with the lambda keyword', 'A method for loop execution', 'A data visualization chart', 'B', 2, 20),
  (12, 'What does EDA stand for in data analysis?', 'Evaluation of Data Accuracy', 'Exploratory Data Analysis', 'External Data Acquisition', 'Entry-level Data Architecture', 'B', 2, 1),
  (12, 'Which python visualization library is built on top of Matplotlib and offers high-level interfaces for drawing statistics charts?', 'NumPy', 'Pandas', 'Seaborn', 'Scipy', 'C', 2, 2),
  (12, 'Which Seaborn function is best to display the correlation matrix as a color-coded grid?', 'sns.lineplot()', 'sns.heatmap()', 'sns.boxplot()', 'sns.scatterplot()', 'B', 2, 3),
  (12, 'To plot the distribution of a single numeric variable, which chart is most appropriate?', 'Scatter plot', 'Pie chart', 'Histogram', 'Line chart', 'C', 2, 4),
  (12, 'Which seaborn function displays a box plot showing quartiles and outliers?', 'sns.boxplot()', 'sns.barplot()', 'sns.kdeplot()', 'sns.stripplot()', 'A', 2, 5),
  (12, 'In Pandas, to group a DataFrame by a column ''Category'' and calculate the mean of ''Sales'', which code is correct?', 'df.groupby(''Category'')[''Sales''].mean()', 'df.group(''Category'').mean(''Sales'')', 'df.pivot(''Category'', ''Sales'')', 'df.aggregate(''Category'', ''mean'')', 'A', 2, 6),
  (12, 'Which matplotlib command is used to display a plot on screen?', 'plt.show()', 'plt.plot()', 'plt.print()', 'plt.render()', 'A', 2, 7),
  (12, 'To analyze the linear relationship between two continuous variables, which plot is best?', 'Histogram', 'Scatter plot', 'Bar chart', 'Pie chart', 'B', 2, 8),
  (12, 'What is the purpose of correlation analysis during EDA?', 'To format databases', 'To measure the strength and direction of the linear relationship between two variables', 'To replace missing values', 'To drop outlier columns', 'B', 2, 9),
  (12, 'A correlation coefficient of +0.02 between two variables implies:', 'Strong positive relationship', 'Strong negative relationship', 'Almost no linear relationship', 'Perfect correlation', 'C', 2, 10),
  (12, 'In Seaborn, which parameter in plotting functions allows you to color data points based on a categorical column (adding a legend group)?', 'color', 'hue', 'style', 'palette', 'B', 2, 11),
  (12, 'Which pandas function creates a cross-tabulation table of two or more factors?', 'pd.crosstab()', 'pd.groupby()', 'pd.concat()', 'pd.merge()', 'A', 2, 12),
  (12, 'To change the title of a plot in Matplotlib, which function do you use?', 'plt.title()', 'plt.label()', 'plt.header()', 'plt.suptitle()', 'A', 2, 13),
  (12, 'An analyst calculates the correlation matrix of df. What is the value along the main diagonal?', '0.0', '1.0', '-1.0', 'Random value', 'B', 2, 14),
  (12, 'What does the code ''sns.pairplot(df)'' do?', 'Plots a single scatter plot', 'Plots pairwise relationships (scatterplots/histograms) for all numeric variables in the DataFrame', 'Creates a correlation heatmap', 'Returns summary statistics', 'B', 2, 15),
  (12, 'An analyst detects outliers using Z-score in Python. What is the standard threshold beyond which a Z-score flags an outlier?', '|Z| > 3', '|Z| > 1', '|Z| > 0.5', '|Z| > 1.96', 'A', 2, 16),
  (12, 'In Pandas, what is the difference between pd.concat() and pd.merge()?', 'concat stacks DataFrames along an axis (rows/columns); merge joins them on matching key columns', 'merge is for SQL tables; concat is for CSVs', 'concat modifies files; merge is in-memory only', 'They are identical functions', 'A', 2, 17),
  (12, 'To convert a string column ''Date'' to datetime objects in Pandas, you use:', 'df[''Date''].astype(datetime)', 'pd.to_datetime(df[''Date''])', 'df[''Date''].format()', 'df[''Date''].convert()', 'B', 2, 18),
  (12, 'How do you calculate correlation in Pandas?', 'df.corr()', 'df.correlation()', 'df.describe()', 'df.cov()', 'A', 2, 19),
  (12, 'Which chart type combines a box plot and a kernel density plot to show the probability density of data at different values?', 'Boxen plot', 'Violin plot', 'Scatter plot', 'Line plot', 'B', 2, 20),
  (13, 'Which chart type is best for showing a trend over time?', 'Bar Chart', 'Pie Chart', 'Line Chart', 'Treemap', 'C', 2, 1),
  (13, 'In Power BI, what does DAX stand for?', 'Data Analysis Expressions', 'Data Aggregation eXpression', 'Digital Analytics eXchange', 'Database Access eXecution', 'A', 2, 2),
  (13, 'Which visual in Power BI acts as an interactive on-page filter for users?', 'Card', 'Slicer', 'Gauge', 'Matrix', 'B', 2, 3),
  (13, 'Which component in Power BI is used to connect to and transform data before loading it into the model?', 'Power BI Desktop View', 'Power Query Editor', 'DAX Editor', 'Power BI Service', 'B', 2, 4),
  (13, 'Which chart is best for showing the distribution of a single numeric variable?', 'Scatter plot', 'Histogram', 'Line chart', 'Pie chart', 'B', 2, 5),
  (13, 'In Power BI data modeling, a relationship connects tables using which key mapping by default?', '1-to-1', '1-to-many', 'many-to-many', 'No key mapping', 'B', 2, 6),
  (13, 'What is a major difference between a Calculated Column and a Measure in DAX?', 'Columns are evaluated at runtime; Measures are saved in the file', 'Calculated columns are evaluated row-by-row during data refresh; Measures are evaluated dynamically on-the-fly when added to visuals', 'Calculated columns are faster than measures', 'Measures only work with text', 'B', 2, 7),
  (13, 'Which DAX function is used to modify the filter context of a calculation (the most powerful function in DAX)?', 'SUM', 'CALCULATE', 'FILTER', 'ALL', 'B', 2, 8),
  (13, 'Why should Pie Charts be avoided when representing more than 5 categories?', 'Power BI doesn''t support it', 'They become hard to read and compare angles/slices accurately compared to a simple bar chart', 'They consume too much database memory', 'They are black and white', 'B', 2, 9),
  (13, 'In Power BI, which view is used to define relationships between tables (e.g. Star Schema)?', 'Report View', 'Data View', 'Model View', 'Query View', 'C', 2, 10),
  (13, 'Which DAX function should you use to divide two metrics to safely handle division by zero errors?', 'The ''/'' operator', 'DIVIDE()', 'SAFE_DIV()', 'IFERROR()', 'B', 2, 11),
  (13, 'What is a Star Schema?', 'A schema with a central fact table surrounded by dimension tables', 'A schema where tables are nested in a circle', 'A schema with no relationships', 'A normalized transactional schema', 'A', 2, 12),
  (13, 'Which visual displays hierarchical data as nested rectangles, colored by categories?', 'Slicer', 'Treemap', 'Waterfall Chart', 'Gauge', 'B', 2, 13),
  (13, 'What does the CALCULATE function do in DAX?', 'Sums values in a column', 'Evaluates an expression in a modified filter context', 'Loops over a table row by row', 'Multiplies two metrics', 'B', 2, 14),
  (13, 'Which DAX function returns the total sum of sales, overriding all user slicer filters on the table?', 'CALCULATE(SUM(Sales[Amount]), FILTER(...))', 'CALCULATE(SUM(Sales[Amount]), ALL(Sales))', 'SUM(Sales[Amount])', 'TOTAL(Sales[Amount])', 'B', 2, 15),
  (13, 'What is the difference between Row Context and Filter Context in DAX?', 'Row context is active during calculated columns (row-by-row); Filter context is active during visual aggregations (slicers/filters)', 'Filter context is for calculated columns; Row context is for measures', 'Row context can only be changed by filters', 'They are identical contexts', 'A', 2, 16),
  (13, 'Which DAX function is a Time Intelligence function that calculates sales from the same period last year?', 'PREVIOUSYEAR()', 'SAMEPERIODLASTYEAR()', 'DATEADD()', 'YOY()', 'B', 2, 17),
  (13, 'In a Star Schema design, what is stored in a Fact Table?', 'Descriptive text attributes (e.g. customer name, product category)', 'Quantitative business metrics and foreign keys (e.g. transaction amount, date key, customer key)', 'System configuration logs', 'SQL index definitions', 'B', 2, 18),
  (13, 'What does the DAX function RELATED() do?', 'Creates a relationship between two tables', 'Returns a value from a related table following an active relationship (on the ''one'' side)', 'Filters a table based on conditions', 'Combines two text strings', 'B', 2, 19),
  (13, 'Why is Import Mode faster than DirectQuery in Power BI?', 'DirectQuery is blocked by firewalls', 'Import mode loads a copy of the data directly into Power BI''s in-memory VertiPaq engine, whereas DirectQuery queries the source database live on every interaction', 'Import mode does not support relationships', 'DirectQuery requires SQL administration', 'B', 2, 20),
  (14, 'Which storytelling framework stands for Situation, Complication, Question, and Answer?', 'SCQA', 'SMART', 'AARRR', 'PDCA', 'A', 2, 1),
  (14, 'According to Edward Tufte, you should maximize the:', 'Clutter-to-Data ratio', 'Data-Ink ratio', 'Color count in charts', 'Page size of reports', 'B', 2, 2),
  (14, 'Which color is universally associated with negative business indicators (e.g., declining profit)?', 'Blue', 'Green', 'Red', 'Yellow', 'C', 2, 3),
  (14, 'The principle that a user should understand the main insight of a chart within 5 seconds is called the:', '5-second rule', '5-color rule', 'Dashboard latency rule', 'Executive summary rule', 'A', 2, 4),
  (14, 'When designing a dashboard layout for users who read left-to-right, where should the most important KPIs be placed?', 'Bottom-right corner', 'Top-left corner', 'Directly in the center', 'In a separate hidden page', 'B', 2, 5),
  (14, 'What is ''Visual Clutter'' in dashboard design?', 'The density of data pixels', 'Non-essential elements (like gridlines, borders, decorative shapes) that distract from the data', 'A high number of active users', 'A database index error', 'B', 2, 6),
  (14, 'Which of the following is a key way to increase the Data-Ink Ratio?', 'Adding 3D effects to bar charts', 'Removing unnecessary gridlines, background shading, and borders from charts', 'Using bold colors for all texts', 'Adding icons next to every number', 'B', 2, 7),
  (14, 'When presenting data insights to a non-technical C-suite executive, you should:', 'Start with detailed statistics formulas and query code', 'Lead with the business impact/insights first, then explain supporting data briefly', 'Show all 50 charts you generated', 'Avoid using colors', 'B', 2, 8),
  (14, 'Gestalt principles of visual design help analysts understand:', 'How databases query tables', 'How humans naturally perceive and group visual elements (proximity, similarity, continuity)', 'How to write SQL window functions', 'How to calculate standard deviation', 'B', 2, 9),
  (14, 'An analyst colors one bar in a bar chart bright blue, and the others grey. This is an example of:', 'Color clutter', 'Pre-attentive attribute highlighting to direct the viewer''s focus', 'Lack of design skills', 'Symmetrical distribution', 'B', 2, 10),
  (14, 'Which of the following describes the ''Complication'' in the SCQA storytelling framework?', 'The final recommendation for action', 'The trigger or problem that disrupted the status quo and needs analysis', 'The current business baseline context', 'The SQL query syntax used', 'B', 2, 11),
  (14, 'Why should you avoid using 3D charts (e.g. 3D pie charts) in data visualization?', 'They require special glasses', 'They distort the perspective, making it difficult for the human eye to compare heights/slices accurately', 'Power BI does not support 3D', 'They slow down server load speeds', 'B', 2, 12),
  (14, 'What is a ''Call to Action'' in a data presentation?', 'A phone call to the client', 'A slide that outlines the specific recommended business decisions based on the insights', 'A database trigger script', 'A marketing CPC campaign', 'B', 2, 13),
  (14, 'Which font property should be used to establish a clear visual hierarchy in reports?', 'Varying font sizes, weights (bold/regular), and colors strategically', 'Using different font families for every word', 'Always using uppercase letters', 'Centering all text fields', 'A', 2, 14),
  (14, 'When designing a dashboard, what is the best practice for using color?', 'Use as many vibrant colors as possible to make it look active', 'Use a neutral palette (greys) with one single accent color to highlight key insights', 'Use black and white only', 'Use different colors for every category', 'B', 2, 15),
  (14, 'In the SCQA framework, where is the analytical question placed?', 'At the very start of the presentation slide', 'Directly after the Situation and Complication, defining what the analysis aims to solve', 'Only in the appendix', 'In the database schema documentation', 'B', 2, 16),
  (14, 'What is the Gestalt principle of ''Proximity'' in visual design?', 'Things that are physically close to each other are perceived as grouped together', 'Things that look similar are grouped', 'Continuous lines are followed', 'Objects are enclosed', 'A', 2, 17),
  (14, 'An analyst presents that sales grew 10% but fails to mention that the industry average was 30% growth. This is a violation of which design principle?', 'Visual clutter', 'Providing proper context for interpretation', 'Data-ink ratio', 'Time boundary', 'B', 2, 18),
  (14, 'Which title is considered an ''Action Title'' for a slide showing a revenue drop?', 'Sales Chart 2026', 'Revenue Declined by 15% due to competitor discount campaigns in the West region', 'Quarterly Report', 'Analysis of sales table', 'B', 2, 19),
  (14, 'How does cognitive load affect dashboard users?', 'It speeds up their calculation capacity', 'High cognitive load (caused by messy layout/clutter) causes mental fatigue and makes it harder to locate insights', 'It encrypts report visuals', 'It has no impact on C-suite decisions', 'B', 2, 20);

-- Update max scores of all test windows to 40 marks
UPDATE public.test_windows SET max_score = 40 WHERE week_number BETWEEN 1 AND 14;
